import { CHARACTER_ANIMATIONS, type CharacterAnimation } from "./character-animation.consts";
import { CHARACTER_TARGETS, type CharacterTarget } from "./character-target.consts";

export const CHARACTER_TARGET_ANIMATION_DURATIONS = {
  [CHARACTER_TARGETS.DAO]: {
    [CHARACTER_ANIMATIONS.IDLE]: 2000,
    [CHARACTER_ANIMATIONS.THROW_BALLON]: 3000,
  },
  [CHARACTER_TARGETS.BAZZI]: {
    [CHARACTER_ANIMATIONS.IDLE]: 2000,
    [CHARACTER_ANIMATIONS.THROW_BALLON]: 3000,
  },
  [CHARACTER_TARGETS.DIZNI]: {
    [CHARACTER_ANIMATIONS.IDLE]: 2000,
    [CHARACTER_ANIMATIONS.THROW_BALLON]: 3000,
  },
  [CHARACTER_TARGETS.EDDI]: {
    [CHARACTER_ANIMATIONS.IDLE]: 2000,
    [CHARACTER_ANIMATIONS.THROW_BALLON]: 3000,
  },
  [CHARACTER_TARGETS.KEPI]: {
    [CHARACTER_ANIMATIONS.IDLE]: 2000,
    [CHARACTER_ANIMATIONS.THROW_BALLON]: 3000,
  },
  [CHARACTER_TARGETS.MARID]: {
    [CHARACTER_ANIMATIONS.IDLE]: 2000,
    [CHARACTER_ANIMATIONS.THROW_BALLON]: 3000,
  },
  [CHARACTER_TARGETS.MOS]: {
    [CHARACTER_ANIMATIONS.IDLE]: 2000,
    [CHARACTER_ANIMATIONS.THROW_BALLON]: 3000,
  },
  [CHARACTER_TARGETS.UNI]: {
    [CHARACTER_ANIMATIONS.IDLE]: 2000,
    [CHARACTER_ANIMATIONS.THROW_BALLON]: 3000,
  },
} as const satisfies Record<CharacterTarget, Record<CharacterAnimation, number>>;
