name: "deploy"

# This will trigger the action on each push to the `release` branch.
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - run: corepack enable
      - run: corepack prepare pnpm --activate
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm run boom-hill-land-web:build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "./apps/boom-hill-land-web/out"

  github-page-deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v5
